In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("employee_data.csv")
df.head()

,EmployeeID,Name,Age,Salary,Department,JoiningDate,Contact,Experience,PerformanceScore
0,1001,James Brown,22.0,45000.0,HR,2022-03-15,james.brownyahoo.com | 6613186091,11,7.1
1,1002,Lucas Green,26.0,42000.0,Finance,2020-06-30,lucas.green@gmail.com | 8219935181,10,8.0
2,1003,Mia Scott,28.0,85000.0,NaN,2022-02-10,mia.scott@yahoo.com | 3194875749,2,NaN
3,1004,Noah Davis,25.0,85000.0,Operations,2014-11-18,noah.davis@gmail.com | 9555979711,8,7.5
4,1005,Alice Martin,NaN,85000.0,Marketing,2022-08-27,alice.martinhotmail.com | 7529170342,7,9.2

In [4]:
#identify missing values
df.describe()

        EmployeeID         Age         Salary  Experience  PerformanceScore
count   202.000000  180.000000     188.000000  202.000000        181.000000
mean   1099.663366   27.694444   61196.808511    8.123762          8.298895
std      58.206576    3.371085   37754.180849    4.575462          0.781522
min    1001.000000   22.000000   -3000.000000    1.000000          7.100000
25%    1049.250000   25.000000   45000.000000    4.000000          7.800000
50%    1099.500000   27.000000   56000.000000    8.000000          8.400000
75%    1149.750000   30.000000   72000.000000   12.000000          8.800000
max    1200.000000   35.000000  150000.000000   15.000000          9.600000

In [9]:

df.isnull().sum()

EmployeeID           0
Name                 0
Age                 22
Salary              14
Department          26
JoiningDate         19
Contact              0
Experience           0
PerformanceScore    21
dtype: int64

In [10]:
import numpy as np

In [ ]:
#replace ag column with mean
mean_age=np.mean(df["Age"])

27.694444444444443

In [12]:
df["Age"]=df["Age"].fillna(df["Age"].mean())

In [13]:
df["Age"]

0      22.000000
1      26.000000
2      28.000000
3      25.000000
4      27.694444
         ...
197    27.694444
198    29.000000
199    22.000000
200    29.000000
201    32.000000
Name: Age, Length: 202, dtype: float64

In [15]:
#replace misisng salary using median
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
df["Salary"]

0      45000.0
1      42000.0
2      85000.0
3      85000.0
4      85000.0
        ...
197    52000.0
198    52000.0
199    45000.0
200    56000.0
201    45000.0
Name: Salary, Length: 202, dtype: float64

In [21]:
#replace department column using the mode
df["Department"]=df["Department"].fillna(df["Department"].mode()[0])

In [17]:
#replace performance_score with mean
df["PerformanceScore"]=df["PerformanceScore"].fillna(df["PerformanceScore"].mean())

In [24]:
df.isnull().sum()

EmployeeID          0
Name                0
Age                 0
Salary              0
Department          0
JoiningDate         0
Contact             0
Experience          0
PerformanceScore    0
dtype: int64

In [23]:
#replace joiningdate with mode
df["JoiningDate"] = df["JoiningDate"].fillna(df["JoiningDate"].mode()[0])

In [29]:
df["JoiningDate"].dtype

dtype('O')

In [31]:
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"])
df["JoiningDate"]

0     2022-03-15
1     2020-06-30
2     2022-02-10
3     2014-11-18
4     2022-08-27
         ...
197   2024-07-31
198   2014-12-29
199   2015-12-03
200   2017-01-26
201   2019-08-28
Name: JoiningDate, Length: 202, dtype: datetime64[ns]

In [37]:
#new col joining year
df["JoiningYear"] = df["JoiningDate"].dt.year

In [41]:
df.head()

,EmployeeID,Name,Age,Salary,Department,JoiningDate,Contact,Experience,PerformanceScore,JoiningYear,JoiningMonth,JoiningDay
0,1001,James Brown,22.000000,45000.0,HR,2022-03-15,james.brownyahoo.com | 6613186091,11,7.100000,2022,3,15
1,1002,Lucas Green,26.000000,42000.0,Finance,2020-06-30,lucas.green@gmail.com | 8219935181,10,8.000000,2020,6,30
2,1003,Mia Scott,28.000000,85000.0,Marketing,2022-02-10,mia.scott@yahoo.com | 3194875749,2,8.298895,2022,2,10
3,1004,Noah Davis,25.000000,85000.0,Operations,2014-11-18,noah.davis@gmail.com | 9555979711,8,7.500000,2014,11,18
4,1005,Alice Martin,27.694444,85000.0,Marketing,2022-08-27,alice.martinhotmail.com | 7529170342,7,9.200000,2022,8,27

In [38]:
df["JoiningMonth"] = df["JoiningDate"].dt.month

In [40]:
df["JoiningDay"] = df["JoiningDate"].dt.day

In [46]:
#no of employee joined before 2019
a=(df["JoiningYear"]<2019).sum()
a

99

In [62]:
#split...
#contact col ->  email  and Phone

df[["Email","Phone"]]=df["Contact"].str.split("|",expand=True)

In [65]:
df.head()

,EmployeeID,Name,Age,Salary,Department,JoiningDate,Contact,Experience,PerformanceScore,JoiningYear,JoiningMonth,JoiningDay,Email,Phone
0,1001,James Brown,22.000000,45000.0,HR,2022-03-15,james.brownyahoo.com | 6613186091,11,7.100000,2022,3,15,james.brownyahoo.com,6613186091
1,1002,Lucas Green,26.000000,42000.0,Finance,2020-06-30,lucas.green@gmail.com | 8219935181,10,8.000000,2020,6,30,lucas.green@gmail.com,8219935181
2,1003,Mia Scott,28.000000,85000.0,Marketing,2022-02-10,mia.scott@yahoo.com | 3194875749,2,8.298895,2022,2,10,mia.scott@yahoo.com,3194875749
3,1004,Noah Davis,25.000000,85000.0,Operations,2014-11-18,noah.davis@gmail.com | 9555979711,8,7.500000,2014,11,18,noah.davis@gmail.com,9555979711
4,1005,Alice Martin,27.694444,85000.0,Marketing,2022-08-27,alice.martinhotmail.com | 7529170342,7,9.200000,2022,8,27,alice.martinhotmail.com,7529170342

In [64]:
df = df.drop(columns=[("Email", "Phone")])

In [ ]:
df["Email"] = df["Email"].str.strip()
df["Phone"] = df["Phone"].str.strip()

In [ ]:
#drop originl contact
#df.drop("Contact", axis=1, inplace=True)

                         Email        Phone
0        james.brownyahoo.com    6613186091
1       lucas.green@gmail.com    8219935181
2         mia.scott@yahoo.com    3194875749
3        noah.davis@gmail.com    9555979711
4     alice.martinhotmail.com    7529170342
..                         ...          ...
197       mia.davis@gmail.com    9613306930
198  john.johnson@company.com    2707112282
199    ethan.harris@gmail.com    8947608302
200    mia.miller@hotmail.com    5632122330
201   ethan.scott@hotmail.com    3377617409

[202 rows x 2 columns]

In [68]:
# create new column bonue - 10% of the salary
df["Bonus"]=df["Salary"]*0.1

In [74]:
df.head(3)

,EmployeeID,Name,Age,Salary,Department,JoiningDate,Contact,Experience,PerformanceScore,JoiningYear,JoiningMonth,JoiningDay,Email,Phone,Bonus,TotalSalary
0,1001,James Brown,22.0,45000.0,HR,2022-03-15,james.brownyahoo.com | 6613186091,11,7.100000,2022,3,15,james.brownyahoo.com,6613186091,4500.0,49500.0
1,1002,Lucas Green,26.0,42000.0,Finance,2020-06-30,lucas.green@gmail.com | 8219935181,10,8.000000,2020,6,30,lucas.green@gmail.com,8219935181,4200.0,46200.0
2,1003,Mia Scott,28.0,85000.0,Marketing,2022-02-10,mia.scott@yahoo.com | 3194875749,2,8.298895,2022,2,10,mia.scott@yahoo.com,3194875749,8500.0,93500.0

In [71]:
#new col -> total sal=sal+bonus
df["TotalSalary"]=df["Salary"]+df["Bonus"]

In [ ]:
#new col -